// let num=prompt("Enter Number:");
// document.writeln(num);
// document.writeln(typeof num);
// let num=parseInt(prompt("Enter Number:"));
// document.writeln(num);
// document.writeln(typeof num);
// let num=parseFloat(prompt("Enter Number:"));
// document.writeln(num);
// document.writeln(typeof num);
// let num=46;
// console.log(num);
// console.log(typeof num);
// console.log(num.toString());
// console.log(typeof num.toString());
// console.log(typeof num);